# Generated by Django 5.1.7 on 2025-03-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='cycles_used',
            new_name='current_cycles_used',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='drop_off_location',
            new_name='dropoff_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='pick_up_location',
            new_name='pickup_location',
        ),
    ]
