# Generated by Django 5.1.7 on 2025-03-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cycles_used_trip_current_cycles_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='current_cycles_used',
            new_name='current_cycle_used',
        ),
    ]
