# Generated by Django 5.1.7 on 2025-03-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trip_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='create',
            new_name='created',
        ),
    ]
